# Generated by Django 5.2.1 on 2025-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectformat',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
